import type { WeddingState } from "./types";

export function defaultWeddingState(): WeddingState {
  return {
    dataVersion: 3,
    weddingDate: "2027-06-20",
    akadTime: "08:00 WIB",
    resepsiTime: "11:00 - 14:00 WIB",
    weddingVenue: "Grand Ballroom Hotel Santika, Jakarta",
    weddingTheme: "Modern Nusantara Elegant (Rose Gold & Gold)",
    totalBudget: 0,
    brideData: {
      cpp: {
        fullName: "",
        nickname: "",
        father: "",
        mother: "",
        phone: "",
        address: "",
      },
      cpw: {
        fullName: "",
        nickname: "",
        father: "",
        mother: "",
        phone: "",
        address: "",
      },
    },
    budgetList: [],
    maharItems: [
      { id: "seed-mahar-1", title: "Logam Mulia Antam 10 Gram", cost: 13500000, ready: false },
      { id: "seed-mahar-2", title: "Set Perhiasan Emas 5 Gram", cost: 6500000, ready: false },
      { id: "seed-mahar-3", title: "Seperangkat Alat Sholat Premium", cost: 1500000, ready: false },
    ],
    seserahanCppToCpw: [
      { id: "seed-se-cpp1", title: "Set Skincare & Cosmetic", cost: 2500000, ready: false },
      { id: "seed-se-cpp2", title: "Tas & Sepatu Pesta CPW", cost: 3500000, ready: false },
      { id: "seed-se-cpp3", title: "Kain Kebaya & Bahan Pakaian", cost: 2000000, ready: false },
    ],
    seserahanCpwToCpp: [
      { id: "seed-se-cpw1", title: "Set Jas Formal & Sepatu Pria", cost: 3000000, ready: false },
      { id: "seed-se-cpw2", title: "Parfum & Grooming Kit", cost: 1500000, ready: false },
    ],
    vendors: [],
    adminDocs: [
      { id: "adm-1", title: "Surat Pengantar dari RT/RW", description: "", doneCpp: false, doneCpw: false, status: null },
      { id: "adm-2", title: "Fotocopy KTP (CPP dan CPW)", description: "", doneCpp: false, doneCpw: false, status: null },
      { id: "adm-3", title: "Fotocopy KK (CPP dan CPW)", description: "", doneCpp: false, doneCpw: false, status: null },
      { id: "adm-4", title: "Fotocopy Akta Kelahiran (CPP dan CPW)", description: "", doneCpp: false, doneCpw: false, status: null },
      { id: "adm-5", title: "Fotocopy Ijazah terakhir (CPP dan CPW)", description: "", doneCpp: false, doneCpw: false, status: null },
      { id: "adm-6", title: "Surat Keterangan Menikah (N1)", description: "", doneCpp: false, doneCpw: false, status: null },
      { id: "adm-7", title: "Surat keterangan asal usul mempelai (N2)", description: "", doneCpp: false, doneCpw: false, status: null },
      { id: "adm-8", title: "Surat Pernyataan persetujuan mempelai (N3)", description: "", doneCpp: false, doneCpw: false, status: null },
      { id: "adm-9", title: "Surat Penyataan tentang orang tua (N4)", description: "", doneCpp: false, doneCpw: false, status: null },
      { id: "adm-10", title: "Foto ukuran 3x4 latar biru (CPP dan CPW)", description: "", doneCpp: false, doneCpw: false, status: null },
      { id: "adm-11", title: "Fotocopy KTP Wali Nikah", description: "", doneCpp: false, doneCpw: false, status: null },
      { id: "adm-12", title: "Fotocopy KTP 2 orang saksi Nikah", description: "", doneCpp: false, doneCpw: false, status: null },
      { id: "adm-13", title: "Keterangan sudah Vaksin TT", description: "", doneCpp: false, doneCpw: false, status: null },
      { id: "kua-1", title: "Daftar ke KUA", description: "", doneCpp: false, doneCpw: false, status: "Belum" },
      { id: "kua-2", title: "Bimbingan Pra-nikah dari KUA", description: "", doneCpp: false, doneCpw: false, status: "Belum" },
    ],
    guests: [],
    checklist: [
      { id: "seed-cl-1", timeframe: "H-12 s/d H-9 Bulan", task: "Menentukan Budget Pernikahan & Konsep Utama", done: false },
      { id: "seed-cl-2", timeframe: "H-12 s/d H-9 Bulan", task: "Booking Tanggal & Venue / Gedung Pernikahan", done: false },
      { id: "seed-cl-3", timeframe: "H-8 s/d H-6 Bulan", task: "Booking Catering", done: false },
      { id: "seed-cl-4", timeframe: "H-8 s/d H-6 Bulan", task: "Booking MUA (Makeup Artist)", done: false },
      { id: "seed-cl-5", timeframe: "H-8 s/d H-6 Bulan", task: "Booking Busana Pengantin", done: false },
      { id: "seed-cl-6", timeframe: "H-8 s/d H-6 Bulan", task: "Booking Dekorasi", done: false },
      { id: "seed-cl-7", timeframe: "H-5 s/d H-3 Bulan", task: "Mengurus Pendaftaran Berkas Administrasi KUA", done: false },
      { id: "seed-cl-8", timeframe: "H-5 s/d H-3 Bulan", task: "Beli / Pesan Mahar & Hantaran Seserahan", done: false },
      { id: "seed-cl-9", timeframe: "H-2 s/d H-1 Bulan", task: "Cetak & Distribusi Undangan", done: false },
      { id: "seed-cl-10", timeframe: "H-2 s/d H-1 Bulan", task: "Buat / Pesan Souvenir", done: false },
      { id: "seed-cl-11", timeframe: "H-2 s/d H-1 Bulan", task: "Fitting Akhir Baju Pengantin & Technical Meeting Vendor", done: false },
      { id: "seed-cl-12", timeframe: "H-1 Minggu s/d H-1 Hari", task: "Gladi Bersih, Perawatan Diri, & Istirahat Cukup", done: false },
    ],
    rundownList: [
      { id: "seed-rd-1", time: "07:30 WIB", activity: "Persiapan Mempelai & MUA Makeup", pic: "MUA & WO" },
      { id: "seed-rd-2", time: "08:30 WIB", activity: "Prosesi Akad Nikah & Ijab Kabul", pic: "Penghulu KUA" },
      { id: "seed-rd-3", time: "11:00 WIB", activity: "Pembukaan Resepsi & Foto Bersama", pic: "MC Resepsi" },
    ],
    committeeList: [
      { id: "seed-cm-1", role: "Saksi Nikah CPP", name: "Bpk. Drs. Soeparno", uniformGiven: false },
      { id: "seed-cm-2", role: "Penerima Tamu 1", name: "Siti & Maya", uniformGiven: false },
      { id: "seed-cm-3", role: "Penerima Tamu 2", name: "Dian & Rina", uniformGiven: false },
      { id: "seed-cm-4", role: "PIC Konsumsi / Catering", name: "Paman Budi", uniformGiven: false },
    ],
  };
}
